name: py37
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21
  - pytorch=1.12
  - torchvision=0.13
  - sympy=1.10
  - matplotlib=3.5
  - pandas=1.3  # Upgraded from 1.1 to match sklearn 1.0 compatibility
  - scikit-learn=1.0
  - pip=22.3
  - openssl=1.1
  - zlib=1.2
  - libpng=1.6
  - freetype=2.12
  - setuptools=65.5
  - rdkit=2024.03.5  # ✅ use Conda-installed RDKit (the one you just installed)
  - tqdm=4.66.1  # Move tqdm from pip to conda, more stable
  - pip:
      - deepchem==2.7.1
      - deeppurpose==0.1.5
      - dgllife==0.3.2
      - hyperopt==0.2.7
      - joblib==1.3.2
      - tensorflow==2.11.0
      - torch-geometric==2.3.1
